version: 2

updates:
  # Firebase Functions dependencies
  - package-ecosystem: "npm"
    directory: "/functions"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 2 # Reduced from 5
    commit-message:
      prefix: "deps(functions)"
      include: "scope"
    groups:
      firebase:
        patterns:
          - "firebase*"
      dev-dependencies:
        patterns:
          - "@types/*"
          - "eslint*"
          - "typescript*"
          - "jest*"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly" # Changed from weekly to monthly
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 2 # Reduced from 3
    commit-message:
      prefix: "deps(actions)"
      include: "scope"
    groups:
      actions:
        patterns:
          - "actions/*"
          - "github/*"

  # Pub dependencies (Flutter)
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 2 # Reduced from 5
    commit-message:
      prefix: "deps(flutter)"
      include: "scope"
    groups:
      flutter-core:
        patterns:
          - "flutter*"
      dev-dependencies:
        patterns:
          - "*_test*"
          - "*_lints*"
