name: toolspace
description: Toolspace micro-tools platform

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0" # Update minimum to match your local Dart version

dependencies:
  flutter:
    sdk: flutter

  # Firebase dependencies for File Merger - Updated to latest compatible versions
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  firebase_storage: ^13.0.2
  cloud_firestore: ^6.0.2
  cloud_functions: ^6.0.2

  # UI and utility dependencies
  file_picker: ^8.1.2
  url_launcher: ^6.3.1
  diff_match_patch: ^0.4.1
  nanoid2: ^2.0.1
  flutter_markdown: ^0.7.4+1
  markdown: ^7.2.2
  csv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - config/pricing.json
