name: toolspace
description: Toolspace micro-tools platform

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0" # Update minimum to match your local Dart version

dependencies:
  flutter:
    sdk: flutter

  # Firebase dependencies for File Merger
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  firebase_storage: ^11.6.0
  cloud_functions: ^4.6.0

  # UI and utility dependencies
  file_picker: ^6.1.1
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # Keep compatible version for now

flutter:
  uses-material-design: true
