name: ✨ Feature Request
description: Suggest an idea for this project
title: "[FEATURE]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please provide as much detail as possible.

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when...
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: Alternatively, we could...
    validations:
      required: false

  - type: dropdown
    id: tool-category
    attributes:
      label: Which tool category does this relate to?
      options:
        - Text Tools
        - Quick Invoice
        - New Tool Category
        - Platform/Infrastructure
        - Authentication/Billing
        - Other

  - type: dropdown
    id: priority
    attributes:
      label: How important is this feature to you?
      options:
        - Nice to have
        - Important
        - Critical
        - Blocking my workflow

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe the specific use case or workflow this feature would enable.
      placeholder: I need this feature because...
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples about the feature request here.
      placeholder: Any additional information that might be helpful

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
