name: 🚨 Auth & Security Gates
on:
    push:
        branches: [main, develop]
    pull_request:
        branches: [main]

jobs:
    flutter-tests:
        name: Flutter Tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: subosito/flutter-action@v2
              with:
                  flutter-version: "3.24.0"
                  channel: "stable"
            - name: Get dependencies
              run: flutter pub get
            - name: Analyze code
              run: flutter analyze
            - name: Run tests
              run: flutter test --coverage
            - name: Upload coverage
              uses: codecov/codecov-action@v3
              with:
                  file: coverage/lcov.info

    functions-tests:
        name: Functions Tests
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: functions
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: "18"
                  cache: "npm"
                  cache-dependency-path: functions/package-lock.json
            - name: Install dependencies
              run: npm ci
            - name: Run tests
              run: npm test
            - name: Build functions
              run: npm run build

    rules-tests:
        name: Security Rules Tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: "18"
            - name: Install Firebase CLI
              run: npm install -g firebase-tools
            - name: Install dependencies
              working-directory: functions
              run: npm ci
            - name: Start emulators and run rules tests
              run: |
                  firebase emulators:exec --only firestore,auth "npm test" --project demo-test
              working-directory: functions

    auth-security-ok:
        name: 🛡️ Auth & Security Composite Check
        runs-on: ubuntu-latest
        needs: [flutter-tests, functions-tests, rules-tests]
        steps:
            - name: All security checks passed
              run: |
                  echo "✅ All auth and security tests passed"
                  echo "✅ Flutter tests: PASSED"
                  echo "✅ Functions tests: PASSED"
                  echo "✅ Security rules tests: PASSED"
                  echo ""
                  echo "🚀 Ready for deployment!"

    block-prod-deploy:
        name: 🚨 Production Deployment Gate
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'
        needs: [auth-security-ok]
        steps:
            - name: Check AUTH-01 Epic Status
              run: |
                  echo "🚨 PRODUCTION DEPLOYMENT BLOCKED"
                  echo ""
                  echo "Reason: AUTH-01 Epic not completed"
                  echo "Required: All auth and security issues must be resolved"
                  echo ""
                  echo "Epic Issues:"
                  echo "- #77 A1 — Auth UI & Flow"
                  echo "- #78 A2 — Auth Service & Guards"
                  echo "- #79 S1 — Security Rules"
                  echo "- #80 S2 — Functions Auth Middleware"
                  echo "- #81 B1 — Stripe User Linking"
                  echo "- #82 B2 — PaywallGuard Integration"
                  echo "- #83 U1 — Account Settings"
                  echo "- #84 D1 — Docs & CI Gates"
                  echo ""
                  echo "⚠️ Remove this step when AUTH-01 is complete"
                  exit 1
