name: Auto-Approve Copilot PRs

on:
    pull_request:
        types: [opened, synchronize, reopened]

permissions:
    contents: read
    pull-requests: write

jobs:
    auto-approve:
        name: Auto-Approve Copilot PRs
        runs-on: ubuntu-latest
        if: |
            github.event.pull_request.user.login == 'app/copilot-swe-agent' ||
            github.event.pull_request.user.login == 'copilot' ||
            github.event.pull_request.user.login == 'github-copilot[bot]' ||
            contains(github.event.pull_request.head.ref, 'copilot/')

        steps:
            - name: Auto-approve Copilot PR
              uses: actions/github-script@v7
              with:
                  script: |
                      const { owner, repo } = context.repo;
                      const pr_number = context.payload.pull_request.number;

                      console.log(`Auto-approving Copilot PR #${pr_number}`);

                      try {
                        await github.rest.pulls.createReview({
                          owner: owner,
                          repo: repo,
                          pull_number: pr_number,
                          event: 'APPROVE',
                          body: '🤖 **AUTO-APPROVED**: This PR was automatically approved because it was created by GitHub Copilot.\n\n✅ Copilot PRs are pre-validated and safe for automatic approval.\n✅ This enables the AUTO-DEV pipeline to proceed without manual intervention.\n\n*Automated by Auto-Approve Copilot PRs workflow*'
                        });

                        console.log(`✅ Successfully auto-approved PR #${pr_number}`);

                        // Add auto-merge label if not already present
                        const { data: pr } = await github.rest.pulls.get({
                          owner: owner,
                          repo: repo,
                          pull_number: pr_number
                        });

                        const labels = pr.labels.map(label => label.name);
                        const needsLabels = [];

                        if (!labels.includes('autodev')) {
                          needsLabels.push('autodev');
                        }
                        if (!labels.includes('auto-merge')) {
                          needsLabels.push('auto-merge');
                        }

                        if (needsLabels.length > 0) {
                          await github.rest.issues.addLabels({
                            owner: owner,
                            repo: repo,
                            issue_number: pr_number,
                            labels: needsLabels
                          });
                          console.log(`✅ Added labels: ${needsLabels.join(', ')}`);
                        }

                      } catch (error) {
                        if (error.status === 422 && error.message.includes('already reviewed')) {
                          console.log(`ℹ️ PR #${pr_number} already has a review from this user`);
                        } else {
                          console.error(`❌ Error auto-approving PR #${pr_number}:`, error);
                          throw error;
                        }
                      }

            - name: Comment on PR
              uses: actions/github-script@v7
              with:
                  script: |
                      const { owner, repo } = context.repo;
                      const pr_number = context.payload.pull_request.number;

                      await github.rest.issues.createComment({
                        owner: owner,
                        repo: repo,
                        issue_number: pr_number,
                        body: '🚀 **AUTO-DEV Pipeline Active**\n\nThis PR has been automatically:\n- ✅ **Approved** by auto-approval workflow\n- 🏷️ **Labeled** for auto-merge\n- 🔄 **Queued** for automatic merging when CI passes\n\n*No further manual action required - the AUTO-DEV pipeline will handle the rest!*'
                      });
