name: "Auto-Track Copilot PRs"

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      approve_mode:
        description: "Run approval script for Copilot PRs"
        required: false
        default: "false"
        type: choice
        options:
          - "true"
          - "false"

permissions:
  contents: read
  pull-requests: write
  issues: write
  checks: read

jobs:
  track-copilot-pr:
    name: "Track Copilot PRs"
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.pull_request.user.login == 'app/copilot-swe-agent'

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4

      - name: "Add Tracking Comment to Copilot PR"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER="${{ github.event.pull_request.number }}"
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_AUTHOR="${{ github.event.pull_request.user.login }}"

          echo "INFO: Processing Copilot PR #$PR_NUMBER"
          echo "INFO: Title: $PR_TITLE"
          echo "INFO: Author: $PR_AUTHOR"

          # Determine PR status
          if [[ "$PR_TITLE" == *"[WIP]"* ]]; then
            PR_STATUS="Work in Progress"
            READY_STATUS="🔄 In Development"
          else
            PR_STATUS="Ready for Review"
            READY_STATUS="✅ Ready for Review"
          fi

          # Add tracking comment instead of approval (GitHub Actions restriction)
          gh pr comment "$PR_NUMBER" --body "🤖 **OPS-Zeta Auto-Dev Agent Notification**

          $READY_STATUS **Copilot PR Detected & Tracked**
          - **Created by:** \`$PR_AUTHOR\`
          - **Status:** $PR_STATUS
          - **Action:** Ready for manual approval or automated script

          **To approve this PR:**
          - Use the approval script: \`npm run approve:copilot\`
          - Or use VS Code task: **OPS-Zeta: Approve Copilot PRs**
          - Or approve manually in the GitHub UI

          This PR was automatically detected by the OPS-Zeta pipeline.

          ---
          *Powered by OPS-Zeta Auto-Dev Pipeline* 🚀"

          echo "✓ Added tracking comment to PR #$PR_NUMBER"

  bulk-approve:
    name: "Bulk Approve Copilot PRs"
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.approve_mode == 'true'

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4

      - name: "Setup Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: "Install Dependencies"
        run: npm install

      - name: "Run Bulk Approval Script"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          echo "INFO: Running bulk approval script for Copilot PRs"
          node scripts/approve-copilot-prs.mjs

          echo "✓ Bulk approval completed"

  status-check:
    name: "Check Copilot PR Status"
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4

      - name: "Check Open Copilot PRs"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "INFO: Checking for open Copilot PRs"

          # Get all open Copilot PRs
          COPILOT_PRS=$(gh pr list --author app/copilot-swe-agent --state open --json number,title,reviewDecision,createdAt)

          if [ -z "$COPILOT_PRS" ] || [ "$COPILOT_PRS" = "[]" ]; then
            echo "✅ No open Copilot PRs found"
            exit 0
          fi

          echo "📋 **Open Copilot PRs Status:**"
          echo "$COPILOT_PRS" | jq -r '.[] | "PR #\(.number): \(.title) | Review: \(.reviewDecision // "PENDING") | Created: \(.createdAt)"'

          # Count PRs by status
          TOTAL_PRS=$(echo "$COPILOT_PRS" | jq 'length')
          APPROVED_PRS=$(echo "$COPILOT_PRS" | jq '[.[] | select(.reviewDecision == "APPROVED")] | length')
          PENDING_PRS=$(echo "$COPILOT_PRS" | jq '[.[] | select(.reviewDecision != "APPROVED")] | length')

          echo ""
          echo "📊 **Summary:**"
          echo "- Total Open PRs: $TOTAL_PRS"
          echo "- Approved PRs: $APPROVED_PRS"
          echo "- Pending Approval: $PENDING_PRS"

          if [ "$PENDING_PRS" -gt 0 ]; then
            echo ""
            echo "💡 **Next Actions:**"
            echo "- Run bulk approval: Use 'OPS-Zeta: Approve Copilot PRs' VS Code task"
            echo "- Manual approval: Review individual PRs in GitHub UI"
            echo "- Script approval: Run 'npm run approve:copilot' in terminal"
          fi