name: PR CI (fast)
on:
  pull_request:
  push:
    branches: [ "feat/**" ]
permissions:
  contents: read
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
jobs:
  flutter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with: { channel: stable }
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test --coverage --tags 'not e2e'
      - run: flutter build web --release
      - uses: actions/upload-artifact@v4
        with: { name: web-dist, path: build/web }

  functions:
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: functions } }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: functions/package-lock.json
      - run: npm ci
      - run: npm run lint
      - run: npm test -- --ci

  security-smoke:
    runs-on: ubuntu-latest
    needs: [flutter, functions]
    steps:
      - uses: actions/checkout@v4
      - run: |
          if [ -f test/security/package.json ]; then
            cd test/security && npm ci && npm run rules:compile || true
          else
            echo "No security smoke present; skipping"
          fi
