name: 🚀 Firebase Hosting Preview Deploy

on:
  pull_request:
    branches:
      - main
    paths:
      - "lib/**"
      - "web/**"
      - "pubspec.yaml"
      - "firebase.json"
      - ".github/workflows/preview-hosting.yml"

concurrency:
  group: preview-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_preview:
    name: Build and Deploy Preview
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🎯 Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: 📦 Get dependencies
        run: flutter pub get

      - name: 🔍 Analyze code
        run: flutter analyze --fatal-infos

      - name: 🧪 Run tests
        run: flutter test

      - name: 🏗️ Build web app
        run: flutter build web --release --pwa-strategy=offline-first

      - name: 📊 Bundle size report
        run: |
          echo "## 📦 Bundle Size Report" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| File | Size |" >> $GITHUB_STEP_SUMMARY
          echo "|------|------|" >> $GITHUB_STEP_SUMMARY

          # Find and report large files
          find build/web -type f -size +100k -exec du -h {} \; | sort -rh | head -20 | while read size file; do
            echo "| ${file#build/web/} | $size |" >> $GITHUB_STEP_SUMMARY
          done

          # Total size
          total=$(du -sh build/web | cut -f1)
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Total build size:** $total" >> $GITHUB_STEP_SUMMARY

      - name: 🚀 Deploy to Firebase Hosting Preview
        id: deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: toolspace-dev
          expires: 7d
          channelId: pr-${{ github.event.pull_request.number }}

      - name: 💬 Comment PR with preview URL
        uses: actions/github-script@v7
        with:
          script: |
            const previewUrl = '${{ steps.deploy.outputs.details_url }}';
            const expiresUrl = '${{ steps.deploy.outputs.expire_time }}';

            const comment = `## 🎉 Preview Deployed!

            Your Toolspace preview is ready:

            🔗 **Preview URL:** ${previewUrl}

            ⏰ **Expires:** ${expiresUrl}

            ### 📊 Performance Tips
            - Test on real devices and networks
            - Check Lighthouse scores (run locally or wait for CI)
            - Verify all 17 tools load correctly
            - Test deferred loading performance

            ### 🧪 Testing Checklist
            - [ ] Home screen loads and displays all tools
            - [ ] Search functionality works
            - [ ] Category filters work
            - [ ] Tools open without errors
            - [ ] Neo-Playground UI renders correctly
            - [ ] Dark mode toggle works

            ---
            _This preview will be automatically deleted after 7 days._`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });

      - name: ✅ Check bundle size budget
        run: |
          MAX_SIZE_MB=5
          TOTAL_SIZE=$(du -sm build/web | cut -f1)

          echo "Bundle size: ${TOTAL_SIZE}MB"
          echo "Budget: ${MAX_SIZE_MB}MB"

          if [ $TOTAL_SIZE -gt $MAX_SIZE_MB ]; then
            echo "❌ Bundle size exceeds budget!"
            echo "Current: ${TOTAL_SIZE}MB, Budget: ${MAX_SIZE_MB}MB"
            exit 1
          else
            echo "✅ Bundle size within budget"
          fi
permissions:
  contents: read
  actions: read
