name: 🎯 Quality & Performance Checks

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main

concurrency:
    group: quality-${{ github.ref }}
    cancel-in-progress: true

jobs:
    test_and_lint:
        name: Tests & Linting
        runs-on: ubuntu-latest

        steps:
            - name: 📥 Checkout
              uses: actions/checkout@v4

            - name: 🎯 Setup Flutter
              uses: subosito/flutter-action@v2
              with:
                  channel: "stable"
                  cache: true

            - name: 📦 Get dependencies
              run: flutter pub get

            - name: 🔍 Analyze
              run: flutter analyze

            - name: 🧪 Run Flutter tests
              run: flutter test --coverage

            - name: 📊 Upload coverage
              uses: codecov/codecov-action@v4
              with:
                  files: ./coverage/lcov.info
                  fail_ci_if_error: false
              env:
                  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

            - name: 🔧 Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "npm"
                  cache-dependency-path: functions/package-lock.json

            - name: 📦 Install functions dependencies
              working-directory: functions
              run: npm ci

            - name: 🧪 Run functions tests
              working-directory: functions
              run: npm test

    bundle_size_check:
        name: Bundle Size Check
        runs-on: ubuntu-latest

        steps:
            - name: 📥 Checkout
              uses: actions/checkout@v4

            - name: 🎯 Setup Flutter
              uses: subosito/flutter-action@v2
              with:
                  channel: "stable"
                  cache: true

            - name: 📦 Get dependencies
              run: flutter pub get

            - name: 🏗️ Build
              run: flutter build web --release --pwa-strategy=offline-first

            - name: 📊 Analyze bundle
              run: |
                  echo "## 📦 Bundle Analysis" >> $GITHUB_STEP_SUMMARY
                  echo "" >> $GITHUB_STEP_SUMMARY

                  # Total size
                  TOTAL_SIZE=$(du -sh build/web | cut -f1)
                  echo "**Total Size:** $TOTAL_SIZE" >> $GITHUB_STEP_SUMMARY
                  echo "" >> $GITHUB_STEP_SUMMARY

                  # Large files
                  echo "### Largest Files" >> $GITHUB_STEP_SUMMARY
                  echo "| File | Size |" >> $GITHUB_STEP_SUMMARY
                  echo "|------|------|" >> $GITHUB_STEP_SUMMARY
                  find build/web -type f -exec du -h {} \; | sort -rh | head -10 | while read size file; do
                    filename=$(echo $file | sed 's|build/web/||')
                    echo "| $filename | $size |" >> $GITHUB_STEP_SUMMARY
                  done

            - name: ✅ Check bundle size budget
              run: |
                  MAX_SIZE_MB=5
                  TOTAL_SIZE_KB=$(du -sk build/web | cut -f1)
                  TOTAL_SIZE_MB=$((TOTAL_SIZE_KB / 1024))

                  echo "Bundle size: ${TOTAL_SIZE_MB}MB (Budget: ${MAX_SIZE_MB}MB)"

                  if [ $TOTAL_SIZE_MB -gt $MAX_SIZE_MB ]; then
                    echo "❌ Bundle size exceeds budget!"
                    exit 1
                  else
                    echo "✅ Bundle size within budget"
                  fi
