name: Security Gates (full)
on:
    pull_request:
        paths:
            - "firestore.rules"
            - "storage.rules"
            - "functions/**"
            - "test/security/**"
        types: [opened, synchronize, labeled, reopened]
    schedule:
        - cron: "0 3 * * *"
    workflow_dispatch:
permissions:
    contents: read
concurrency:
    group: sec-${{ github.ref }}
    cancel-in-progress: true
jobs:
    rules-tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with: { node-version: 20 }
            - name: Install Firebase CLI
              run: npm install -g firebase-tools
            - name: Install security test dependencies
              run: cd test/security && npm ci
            - name: Setup emulators and run rules tests
              run: |
                  # Create minimal firebase.json with only storage config (no hosting/webframeworks)
                  cat > firebase-emulators.json << 'EOF'
                  {
                    "storage": {
                      "rules": "storage.rules"
                    },
                    "firestore": {
                      "rules": "firestore.rules"
                    }
                  }
                  EOF
                  # Temporarily use minimal config
                  mv firebase.json firebase.json.bak
                  mv firebase-emulators.json firebase.json
                  # Start emulators in background
                  (firebase emulators:start --only auth,firestore,storage --project demo-toolspace &)
                  sleep 10
                  # Run tests
                  cd test/security && npm run test:rules
                  # Restore original firebase.json
                  cd .. && mv firebase.json.bak firebase.json || true

    e2e-auth-quota:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with: { node-version: 20 }
            - run: |
                  cd test/security || exit 0
                  npm ci
                  npx playwright install --with-deps chromium
                  (firebase emulators:start --only auth,firestore,storage --project demo-toolspace &)
                  sleep 8
                  npx playwright test || npx playwright test --reporter=line
