name: UX Smoke Tests

on:
    pull_request:
        branches: [main, feat/**]
        paths:
            - "lib/**"
            - "test/**"
            - "pubspec.yaml"
            - ".github/workflows/ux-smoke.yml"

permissions:
    contents: read

# Cancel in-progress runs when a new commit is pushed
concurrency:
    group: ci-${{ github.ref }}
    cancel-in-progress: true

jobs:
    flutter-tests:
        name: Flutter Tests (Golden + Navigation)
        runs-on: ubuntu-latest
        timeout-minutes: 15

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Flutter
              uses: subosito/flutter-action@v2
              with:
                  channel: stable
                  cache: true

            - name: Install dependencies
              run: flutter pub get

            - name: Run Flutter tests (includes golden tests)
              run: flutter test --reporter expanded

            - name: Build web app
              run: flutter build web --release

            - name: Upload web build artifact
              uses: actions/upload-artifact@v4
              with:
                  name: web-build
                  path: build/web/
                  retention-days: 1

    e2e-tests:
        name: Playwright E2E Tests
        runs-on: ubuntu-latest
        needs: flutter-tests
        timeout-minutes: 10

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "npm"
                  cache-dependency-path: test/e2e/package-lock.json

            - name: Download web build artifact
              uses: actions/download-artifact@v4
              with:
                  name: web-build
                  path: build/web/

            - name: Install E2E dependencies
              working-directory: test/e2e
              run: npm ci

            - name: Install Playwright browsers
              working-directory: test/e2e
              run: npx playwright install --with-deps chromium

            - name: Start web server in background
              working-directory: test/e2e
              run: |
                  npm run serve &
                  echo "Waiting for server to start..."
                  timeout 30 bash -c 'until curl -s http://localhost:4173 > /dev/null; do sleep 1; done'
                  echo "Server is ready!"

            - name: Run Playwright tests
              working-directory: test/e2e
              run: npm test

            - name: Upload test artifacts (screenshots, videos)
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: ui-smoke-artifacts
                  path: test/e2e/.artifacts/
                  retention-days: 7

            - name: Upload test report
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: playwright-report
                  path: test/e2e/.artifacts/html-report/
                  retention-days: 7
